## Imports

In [1]:
import numpy as np
import pandas as pd
import os

## Show experiment config

In [18]:
# DuckDB nutzen, um die Daten zu aggregieren
con = duckdb.connect()

query = f"""

    SELECT 
        "experiment"."config" AS config, 
    FROM read_parquet('{parquet_files}')
    LIMIT(1) 
--TODO: change file write so that config (world) is only in first parquet file
"""

result = con.execute(query).df()

result

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  config
0  world=WorldConfig(grid_rows=16, grid_cols=16) agent=AgentConfig(type=<AgentType.SARSA: 'sarsa'>, alpha=0.05, gamma=0.99, epsilon=0.5, epsilon_decay=0.9995, epsilon_min=0.01) training=TrainingConfig(num_episodes=10000, max_steps_per_episode=100, validate_interval=100) rewards=RewardsConfig(default=-1, invalid=-100, wall=-10) files=FilesConfig(experiment_dir='experiments', board='board.npy', output_prefix='board_with_path', q_table_prefix='q_table', training_path_prefix='training_path_and_rewards')

In [25]:
import duckdb
from IPython.display import Markdown, display


# Query all experiments
results = duckdb.query("""
    SELECT 
        experiment.episode.nr as episode_number,
        experiment.episode.mode as mode,
        len(experiment.episode.steps) as num_steps,
        experiment.episode.steps[1].reward_to_go as total_reward
    FROM read_parquet('experiments/experiment_*.parquet')
    WHERE mode = 'validate'
    ORDER BY episode_number
""").df()

# Note: reward_to_go is only accumulated in validation epochs
display(Markdown("# Reward in Episode"))
pd.set_option('display.max_rows', None)
results

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

# Reward in Episode

    episode_number      mode  num_steps  total_reward
0              100  validate        100        -100.0
1              200  validate        100        -100.0
2              300  validate        100        -100.0
3              400  validate        100        -100.0
4              500  validate        100        -100.0
5              600  validate        100        -100.0
6              700  validate        100        -100.0
7              800  validate        100        -100.0
8              900  validate        100        -100.0
9             1000  validate        100        -100.0
10            1100  validate        100        -100.0
11            1200  validate        100        -100.0
12            1300  validate        100        -100.0
13            1400  validate        100        -100.0
14            1500  validate        100        -100.0
15            1600  validate        100        -100.0
16            1700  validate        100        -100.0
17            1800  validate        100        -100.0
18            1900  validate        100        -100.0
19            2000  validate        100        -100.0
20            2100  validate        100        -100.0
21            2200  validate        100        -100.0
22            2300  validate        100        -100.0
23            2400  validate        100        -100.0
24            2500  validate        100        -100.0
25            2600  validate        100        -100.0
26            2700  validate        100        -100.0
27            2800  validate        100        -100.0
28            2900  validate        100        -100.0
29            3000  validate        100        -100.0
30            3100  validate        100        -100.0
31            3200  validate        100        -100.0
32            3300  validate        100        -100.0
33            3400  validate        100        -100.0
34            3500  validate        100        -100.0
35            3600  validate        100        -100.0
36            3700  validate        100        -100.0
37            3800  validate        100        -100.0
38            3900  validate        100        -100.0
39            4000  validate        100        -100.0
40            4100  validate        100        -100.0
41            4200  validate        100        -100.0
42            4300  validate        100        -100.0
43            4400  validate        100        -100.0
44            4500  validate        100        -100.0
45            4600  validate        100        -100.0
46            4700  validate        100        -100.0
47            4800  validate        100        -100.0
48            4900  validate        100        -100.0
49            5000  validate        100        -100.0
50            5100  validate        100        -100.0
51            5200  validate         62         -62.0
52            5300  validate        100        -100.0
53            5400  validate        100        -100.0
54            5500  validate         52         -52.0
55            5600  validate        100        -100.0
56            5700  validate         48         -48.0
57            5800  validate         48         -48.0
58            5900  validate         48         -48.0
59            6000  validate         48         -48.0
60            6100  validate         48         -48.0
61            6200  validate         48         -48.0
62            6300  validate         48         -48.0
63            6400  validate         48         -48.0
64            6500  validate         48         -48.0
65            6600  validate         48         -48.0
66            6700  validate         48         -48.0
67            6800  validate         48         -48.0
68            6900  validate         48         -48.0
69            7000  validate        100        -100.0
70            7100  validate         48         -48.0
71            7200  validate         48         -48.0
72            7300  validate         48         -48.0
73            7400  validate         48         -48.0
74            7500  validate         48         -48.0
75            7600  validate         48         -48.0
76            7700  validate         48         -48.0
77            7800  validate         48         -48.0
78            7900  validate         48         -48.0
79            8000  validate         48         -48.0
80            8100  validate         48         -48.0
81            8200  validate         48         -48.0
82            8300  validate         48         -48.0
83            8400  validate         48         -48.0
84            8500  validate         48         -48.0
85            8600  validate         48         -48.0
86            8700  validate         48         -48.0
87            8800  validate        100        -100.0
88            8900  validate         48         -48.0
89            9000  validate         48         -48.0
90            9100  validate         48         -48.0
91            9200  validate         48         -48.0
92            9300  validate         48         -48.0
93            9400  validate         48         -48.0
94            9500  validate         48         -48.0
95            9600  validate         48         -48.0
96            9700  validate         48         -48.0
97            9800  validate         48         -48.0
98            9900  validate         48         -48.0
99           10000  validate         48         -48.0

# Find all steps where agent runs against a wall and if it was due to epsilon action

In [26]:
import duckdb

# Pfad zu deinen Dateien (nutzt Wildcards für alle Episoden)
parquet_files = "./experiments/experiment_*.parquet"

# DuckDB nutzen, um die Daten zu aggregieren
con = duckdb.connect()

query = f"""
SELECT * FROM(
    SELECT 
        "experiment"."episode"."nr" AS episode_number, 
        "experiment"."episode"."mode" AS episode_mode,  
        step.reward AS reward, 
        -- step.strategy AS strategy,
        COUNT(*) AS count
    FROM read_parquet('{parquet_files}')
    CROSS JOIN UNNEST("experiment"."episode"."steps") AS t(step) 
    GROUP BY episode_number, episode_mode, reward
    ORDER BY episode_number, episode_mode, reward)
    WHERE reward=-10
"""

result = con.execute(query).df()

result

# Optional: Als eine einzige CSV oder Parquet zusammenfassen
# con.execute(f"COPY ({query}) TO 'aggregated_rewards.csv' (HEADER, DELIMITER ',')")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

      episode_number episode_mode  reward  count
0                  1        train   -10.0      9
1                  2        train   -10.0     19
2                  3        train   -10.0     12
3                  4        train   -10.0      7
4                  5        train   -10.0      5
5                  6        train   -10.0      6
6                  7        train   -10.0     19
7                  8        train   -10.0      8
8                  9        train   -10.0     12
9                 10        train   -10.0      7
10                11        train   -10.0      7
11                12        train   -10.0      2
12                13        train   -10.0      9
13                14        train   -10.0      3
14                15        train   -10.0      8
15                16        train   -10.0     12
16                17        train   -10.0     11
17                18        train   -10.0     17
18                19        train   -10.0      5
19                20        train   -10.0     10
20                21        train   -10.0     10
21                22        train   -10.0      3
22                23        train   -10.0      9
23                24        train   -10.0     16
24                25        train   -10.0      1
25                26        train   -10.0      3
26                27        train   -10.0      3
27                28        train   -10.0      6
28                29        train   -10.0      5
29                30        train   -10.0     14
30                31        train   -10.0      8
31                32        train   -10.0      3
32                33        train   -10.0     15
33                34        train   -10.0      6
34                35        train   -10.0      5
35                36        train   -10.0      4
36                37        train   -10.0      9
37                38        train   -10.0      8
38                39        train   -10.0      7
39                40        train   -10.0     16
40                41        train   -10.0     25
41                42        train   -10.0     14
42                43        train   -10.0      8
43                44        train   -10.0     11
44                45        train   -10.0     10
45                46        train   -10.0      6
46                47        train   -10.0     10
47                48        train   -10.0     12
48                49        train   -10.0     12
49                50        train   -10.0      8
50                51        train   -10.0      7
51                52        train   -10.0      2
52                53        train   -10.0     11
53                54        train   -10.0      3
54                55        train   -10.0     15
55                56        train   -10.0     11
56                57        train   -10.0     16
57                58        train   -10.0      6
58                59        train   -10.0     16
59                60        train   -10.0      5
60                61        train   -10.0      3
61                62        train   -10.0      4
62                63        train   -10.0      9
63                64        train   -10.0      5
64                65        train   -10.0      7
65                66        train   -10.0      9
66                67        train   -10.0      2
67                68        train   -10.0      3
68                69        train   -10.0     10
69                70        train   -10.0      8
70                71        train   -10.0      8
71                72        train   -10.0     11
72                73        train   -10.0      5
73                74        train   -10.0      4
74                75        train   -10.0      3
75                76        train   -10.0     17
76                77        train   -10.0      5
77                78        train   -10.0     10
78                79        train   -10.0      6
79                80        train   -10.0      8
80                81        train   -10.0      6
81                82        train   -10.0     18
82                83        train   -10.0      6
83                84        train   -10.0     18
84                85        train   -10.0      7
85                86        train   -10.0      3
86                87        train   -10.0      4
87                88        train   -10.0      4
88                89        train   -10.0      4
89                90        train   -10.0     11
90                91        train   -10.0     15
91                92        train   -10.0      6
92                93        train   -10.0     12
93                94        train   -10.0     25
94                95        train   -10.0      9
95                96        train   -10.0      6
96                98        train   -10.0      8
97                99        train   -10.0      3
98               101        train   -10.0     10
99               102        train   -10.0     15
100              103        train   -10.0      7
101              104        train   -10.0     20
102              105        train   -10.0      5
103              106        train   -10.0     15
104              107        train   -10.0      3
105              108        train   -10.0      4
106              109        train   -10.0     15
107              110        train   -10.0     12
108              111        train   -10.0     11
109              112        train   -10.0      1
110              113        train   -10.0     10
111              114        train   -10.0     10
112              115        train   -10.0      5
113              116        train   -10.0     18
114              117        train   -10.0      3
115              118        train   -10.0      6
116              119        train   -10.0     13
117              120        train   -10.0      8
118              121        train   -10.0      5
119              122        train   -10.0      6
120              123        train   -10.0     17
121              124        train   -10.0     11
122              125        train   -10.0      7
123              126        train   -10.0      5
124              127        train   -10.0      9
125              128        train   -10.0      8
126              129        train   -10.0     16
127              130        train   -10.0      9
128              131        train   -10.0      8
129              132        train   -10.0      6
130              133        train   -10.0     10
131              134        train   -10.0      8
132              135        train   -10.0      4
133              136        train   -10.0      7
134              137        train   -10.0     11
135              138        train   -10.0      2
136              139        train   -10.0      7
137              140        train   -10.0     11
138              141        train   -10.0     12
139              142        train   -10.0      4
140              143        train   -10.0      8
141              144        train   -10.0      7
142              145        train   -10.0      7
143              146        train   -10.0      7
144              147        train   -10.0      9
145              148        train   -10.0     11
146              149        train   -10.0     16
147              150        train   -10.0      5
148              151        train   -10.0      3
149              152        train   -10.0      5
150              153        train   -10.0      2
151              154        train   -10.0      4
152              155        train   -10.0      7
153              156        train   -10.0     10
154              157        train   -10.0      4
155              158        train   -10.0      4
156              159        train   -10.0      9
157              160        train   -10.0      6
158              161        train   -10.0      9
159              162        train   -10.0     10
160              163        train   -10.0      9
161              164        train   -10.0     17
162              165        train   -10.0     11
163              166        train   -10.0     14
164              167        train   -10.0      4
165              168        train   -10.0      2
166              169        train   -10.0      3
167              170        train   -10.0     11
168              171        train   -10.0      1
169              172        train   -10.0      5
170              173        train   -10.0      2
171              174        train   -10.0     13
172              175        train   -10.0      6
173              176        train   -10.0      1
174              177        train   -10.0      1
175              178        train   -10.0     16
176              179        train   -10.0      4
177              180        train   -10.0      4
178              181        train   -10.0      3
179              182        train   -10.0     11
180              183        train   -10.0     10
181              184        train   -10.0     14
182              185        train   -10.0     10
183              186        train   -10.0     11
184              187        train   -10.0      6
185              188        train   -10.0      9
186              189        train   -10.0      3
187              190        train   -10.0      7
188              191        train   -10.0      7
189              192        train   -10.0      4
190              193        train   -10.0      6
191              194        train   -10.0      4
192              195        train   -10.0     12
193              196        train   -10.0     16
194              197        train   -10.0     14
195              198        train   -10.0      4
196              199        train   -10.0      8
197              201        train   -10.0      9
198              202        train   -10.0     10
199              203        train   -10.0     14
200              204        train   -10.0      7
201              205        train   -10.0     20
202              206        train   -10.0      9
203              207        train   -10.0      6
204              208        train   -10.0      4
205              209        train   -10.0     15
206              210        train   -10.0      5
207              211        train   -10.0      8
208              212        train   -10.0     20
209              213        train   -10.0      8
210              214        train   -10.0      3
211              215        train   -10.0      7
212              216        train   -10.0      3
213              217        train   -10.0      6
214              218        train   -10.0      7
215              219        train   -10.0     13
216              220        train   -10.0     13
217              221        train   -10.0     16
218              222        train   -10.0      6
219              223        train   -10.0      3
220              224        train   -10.0      4
221              225        train   -10.0      3
222              226        train   -10.0      6
223              227        train   -10.0      3
224              228        train   -10.0      6
225              229        train   -10.0      5
226              230        train   -10.0      6
227              231        train   -10.0     14
228              232        train   -10.0      7
229              233        train   -10.0     10
230              234        train   -10.0      8
231              235        train   -10.0     12
232              236        train   -10.0      9
233              237        train   -10.0      6
234              238        train   -10.0      6
235              239        train   -10.0     10
236              240        train   -10.0     12
237              241        train   -10.0      8
238              242        train   -10.0      8
239              243        train   -10.0      9
240              244        train   -10.0     15
241              245        train   -10.0     10
242              246        train   -10.0      7
243              247        train   -10.0     10
244              248        train   -10.0      4
245              249        train   -10.0      4
246              250        train   -10.0      7
247              251        train   -10.0     11
248              252        train   -10.0     11
249              253        train   -10.0      1
250              254        train   -10.0      4
251              255        train   -10.0     11
252              256        train   -10.0     10
253              257        train   -10.0      7
254              258        train   -10.0      5
255              259        train   -10.0      9
256              260        train   -10.0      6
257              261        train   -10.0     12
258              262        train   -10.0      5
259              263        train   -10.0     14
260              264        train   -10.0      8
261              265        train   -10.0     11
262              266        train   -10.0      8
263              267        train   -10.0      6
264              268        train   -10.0      5
265              269        train   -10.0      7
266              270        train   -10.0      9
267              271        train   -10.0     11
268              272        train   -10.0      5
269              273        train   -10.0      5
270              274        train   -10.0     16
271              275        train   -10.0      4
272              276        train   -10.0      6
273              277        train   -10.0     10
274              278        train   -10.0     12
275              279        train   -10.0      7
276              280        train   -10.0      7
277              281        train   -10.0      8
278              282        train   -10.0      5
279              283        train   -10.0      9
280              284        train   -10.0      6
281              285        train   -10.0      6
282              286        train   -10.0      3
283              287        train   -10.0     11
284              288        train   -10.0      7
285              289        train   -10.0     15
286              290        train   -10.0     10
287              291        train   -10.0     12
288              292        train   -10.0      6
289              293        train   -10.0      5
290              294        train   -10.0     23
291              295        train   -10.0      4
292              296        train   -10.0      8
293              297        train   -10.0      6
294              298        train   -10.0     11
295              299        train   -10.0     12
296              301        train   -10.0     13
297              302        train   -10.0     13
298              303        train   -10.0      8
299              304        train   -10.0      7
300              305        train   -10.0      3
301              306        train   -10.0      7
302              307        train   -10.0      6
303              308        train   -10.0      8
304              309        train   -10.0     10
305              310        train   -10.0      7
306              311        train   -10.0      3
307              312        train   -10.0     11
308              313        train   -10.0      9
309              314        train   -10.0      7
310              315        train   -10.0     10
311              316        train   -10.0      1
312              317        train   -10.0      7
313              318        train   -10.0      4
314              319        train   -10.0      5
315              320        train   -10.0     10
316              321        train   -10.0      7
317              322        train   -10.0      5
318              323        train   -10.0     11
319              324        train   -10.0      7
320              325        train   -10.0      6
321              326        train   -10.0      9
322              327        train   -10.0      5
323              328        train   -10.0     10
324              329        train   -10.0      2
325              330        train   -10.0      9
326              331        train   -10.0     11
327              332        train   -10.0      7
328              333        train   -10.0     12
329              334        train   -10.0     27
330              335        train   -10.0      9
331              336        train   -10.0      6
332              337        train   -10.0      9
333              338        train   -10.0     10
334              339        train   -10.0     11
335              340        train   -10.0      5
336              341        train   -10.0     20
337              342        train   -10.0     10
338              343        train   -10.0      8
339              344        train   -10.0      9
340              345        train   -10.0      8
341              346        train   -10.0     14
342              347        train   -10.0      5
343              348        train   -10.0      4
344              349        train   -10.0     14
345              350        train   -10.0     10
346              351        train   -10.0     10
347              352        train   -10.0      9
348              353        train   -10.0      6
349              354        train   -10.0      8
350              355        train   -10.0     11
351              356        train   -10.0      3
352              357        train   -10.0      8
353              358        train   -10.0     10
354              359        train   -10.0      2
355              360        train   -10.0      6
356              361        train   -10.0      2
357              362        train   -10.0      7
358              363        train   -10.0     16
359              364        train   -10.0      5
360              365        train   -10.0      4
361              366        train   -10.0      9
362              367        train   -10.0      3
363              368        train   -10.0      2
364              369        train   -10.0      6
365              370        train   -10.0      6
366              371        train   -10.0      4
367              372        train   -10.0      8
368              373        train   -10.0     11
369              374        train   -10.0      9
370              375        train   -10.0     11
371              376        train   -10.0      7
372              377        train   -10.0     11
373              378        train   -10.0      6
374              379        train   -10.0      2
375              380        train   -10.0      3
376              381        train   -10.0      4
377              382        train   -10.0      1
378              383        train   -10.0      6
379              384        train   -10.0     14
380              385        train   -10.0     11
381              386        train   -10.0     13
382              387        train   -10.0      6
383              388        train   -10.0     10
384              389        train   -10.0      6
385              390        train   -10.0     14
386              391        train   -10.0      3
387              392        train   -10.0      9
388              394        train   -10.0     14
389              395        train   -10.0     12
390              396        train   -10.0      7
391              397        train   -10.0      1
392              398        train   -10.0      9
393              399        train   -10.0      5
394              401        train   -10.0      4
395              402        train   -10.0      6
396              403        train   -10.0      8
397              404        train   -10.0      4
398              405        train   -10.0      8
399              406        train   -10.0      2
400              407        train   -10.0      5
401              408        train   -10.0     14
402              409        train   -10.0      4
403              410        train   -10.0      8
404              411        train   -10.0     11
405              412        train   -10.0      4
406              413        train   -10.0      7

In [17]:
# DuckDB nutzen, um die Daten zu aggregieren
con = duckdb.connect()

query = f"""

    SELECT 
        "experiment"."config" AS config, 
    FROM read_parquet('{parquet_files}')
    LIMIT(1) 
--TODO: change file write so that config (world) is only in first parquet file
"""

result = con.execute(query).df()

result

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  config
0  world=WorldConfig(grid_rows=16, grid_cols=16) agent=AgentConfig(type=<AgentType.SARSA: 'sarsa'>, alpha=0.05, gamma=0.99, epsilon=0.5, epsilon_decay=0.9995, epsilon_min=0.01) training=TrainingConfig(num_episodes=10000, max_steps_per_episode=100, validate_interval=100) rewards=RewardsConfig(default=-1, invalid=-100, wall=-10) files=FilesConfig(experiment_dir='experiments', board='board.npy', output_prefix='board_with_path', q_table_prefix='q_table', training_path_prefix='training_path_and_rewards')